name: Build

on:
  push:
    tags: [v*.*.*]
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "app"
      - name: Build
        if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
        run: cargo build
      - name: Build(release)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: cargo build --release
      - name: test
        run: cargo test
      - name: Generate license.html
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          cargo install --locked cargo-about
          cargo about generate about.hbs > license.html
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: |
            ./target/*/packet-flow
            license.html
      - name: Package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          tar czvf packet-flow_"$RUNNER_OS"_x64.tgz ./target/release/packet-flow license.html
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ./packet-flow_*_x64.tgz
